### PR TITLE
feat: enables the use of user defined statistical measures

### LINKED ISSUE #7: enable usage of user defined statistical measures

### PR DESCRIPTION
**Pull request by MichaMans**
necessary revision of the statistical measure attribute of the data_types to use with user defined functions, see: https://github.com/RWTH-EBC/ebcpy/pull/25 closes #7

### CODE REVIEW

**Comment by MichaMans** [comment]
@FWuellhorst is that working? because if you set the property as string while a function should be used it might not work as expected or? I think the workaround besides the proposed could be to check in the visualizer if its a callable and then call the name, otherwise the string ist used.

**Comment by FWuellhorst** [comment]
We always use the object `_stat_analyzer` to calculate and `_stat_meas` to indicate what type of measure is used. This way, we don't need to change anything besides the `Goals` class.

**Comment by MichaMans** [comment]
you are right. I overlook that getter and that it returns _sta_meas. It all works.

**Review by FWuellhorst — APPROVED** [review]

**Comment by FWuellhorst** [comment]
@MichaMans : Thanks for the changes! I again forgot to review and merge. Feel free to merge.

**Pull request merged**
